"""add report stale hours setting for alerts

Revision ID: 012519904089
Revises: 4f12fc0b1aa1
Create Date: 2026-07-23 05:59:08.125465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012519904089'
down_revision = '4f12fc0b1aa1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('report_stale_hours', sa.Integer(), nullable=False, server_default='48'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('report_stale_hours')

    # ### end Alembic commands ###
