"""add finance_id to vet_visits and diseases (band 261)

Revision ID: 0228f14ddc52
Revises: c22a228b9094
Create Date: 2026-08-27 02:30:13.859757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0228f14ddc52'
down_revision = 'c22a228b9094'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_diseases_finance_id_finance', 'finance', ['finance_id'], ['id'])

    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_vet_visits_finance_id_finance', 'finance', ['finance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vet_visits_finance_id_finance', type_='foreignkey')
        batch_op.drop_column('finance_id')

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diseases_finance_id_finance', type_='foreignkey')
        batch_op.drop_column('finance_id')

    # ### end Alembic commands ###
