"""add telegram_chat_id to users

Revision ID: 0251d60fc028
Revises: 53536ae05ec9
Create Date: 2026-08-08 17:19:33.620953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0251d60fc028'
down_revision = '53536ae05ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_chat_id', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telegram_chat_id')

    # ### end Alembic commands ###
