"""add newborn mother postpartum protocol settings

Revision ID: 063cb8138ee1
Revises: 425821f5c789
Create Date: 2026-08-11 16:59:56.783498

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '063cb8138ee1'
down_revision = '425821f5c789'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('colostrum_window_hours', sa.Integer(), nullable=False, server_default='4'))
        batch_op.add_column(sa.Column('placenta_check_hours', sa.Integer(), nullable=False, server_default='6'))
        batch_op.add_column(sa.Column('postpartum_mother_followup_days', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('postpartum_mother_followup_days')
        batch_op.drop_column('placenta_check_hours')
        batch_op.drop_column('colostrum_window_hours')

    # ### end Alembic commands ###
