"""add farm settings table

Revision ID: 066366b341e0
Revises: c4e36a948301
Create Date: 2026-07-22 17:13:51.417088

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '066366b341e0'
down_revision = 'c4e36a948301'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farm_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('gestation_days', sa.Integer(), nullable=False),
    sa.Column('sponge_duration_days', sa.Integer(), nullable=False),
    sa.Column('ram_entry_after_sponge_days', sa.Integer(), nullable=False),
    sa.Column('pre_birth_feed_change_days', sa.Integer(), nullable=False),
    sa.Column('postpartum_feed_days', sa.Integer(), nullable=False),
    sa.Column('male_sale_after_birth_days', sa.Integer(), nullable=False),
    sa.Column('alert_before_days', sa.Integer(), nullable=False),
    sa.Column('vaccination_repeat_days', sa.Integer(), nullable=False),
    sa.Column('isolation_days', sa.Integer(), nullable=False),
    sa.Column('doctor_check_hours', sa.Integer(), nullable=False),
    sa.Column('postpartum_vaccination_days', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('farm_settings')
    # ### end Alembic commands ###
