"""add name_en to symptoms

Revision ID: 0b8f5e2ebf87
Revises: 97ab5527ce45
Create Date: 2026-09-08 15:34:06.158149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b8f5e2ebf87'
down_revision = '97ab5527ce45'
branch_labels = None
depends_on = None


# بند إصلاح (طلبك الصريح، صورة حية: دكتور حسابه إنجليزي شاف قائمة
# الأعراض بالمساعد التشخيصي عربي بحت) — بذور إنجليزية للأعراض السبعة
# والعشرين المزروعة أصلاً بـ`flask seed` (`DEFAULT_SYMPTOMS_PRIMARY`
# + `DISEASE_SYMPTOMS` بـ`app/cli.py`)، عشان أي مزرعة شغّالة أصلاً
# تلقط الترجمة فوراً بمجرد ترقية قاعدتها — بدون انتظار عضو يدخل
# ويعبّيها يدوياً واحدة وحدة.
_SYMPTOM_TRANSLATIONS = {
    "حرارة": "Fever",
    "إسهال": "Diarrhea",
    "عرج": "Lameness",
    "سعال وصعوبة تنفس": "Coughing and difficulty breathing",
    "تورم أو احمرار بالضرع": "Udder swelling or redness",
    "حكة وتساقط شعر": "Itching and hair loss",
    "تقرحات بالفم أو القوائم": "Mouth or leg sores",
    "إفرازات من العين": "Eye discharge",
    "تيبّس بالعضلات وتشنجات": "Muscle stiffness and spasms",
    "ضعف عام وعدم قدرة على الوقوف": "General weakness, unable to stand",
    "بثور أو حبوب على الجلد": "Skin blisters or bumps",
    "فقدان وزن رغم الأكل": "Weight loss despite eating",
    "عمى مفاجئ / عتامة العين": "Sudden blindness / eye cloudiness",
    "انخفاض إنتاج الحليب المفاجئ": "Sudden drop in milk production",
    "تكتل أو تغيّر قوام الحليب": "Milk clotting or texture change",
    "تقشّر بالجلد": "Skin flaking",
    "شحوب الأغشية المخاطية": "Pale mucous membranes",
    "انتفاخ بالبطن": "Bloating",
    "جفاف": "Dehydration",
    "إفرازات من الأنف": "Nasal discharge",
    "دم بالبراز": "Blood in stool",
    "ضعف حاد مفاجئ": "Sudden acute weakness",
    "سيلان لعاب زائد": "Excessive drooling",
    "رائحة كريهة من الظلف": "Foul odor from the hoof",
    "احمرار أو تورم بين الأصابع": "Redness or swelling between the toes",
    "احمرار العين": "Eye redness",
    "تورّم الجفن": "Eyelid swelling",
    "صرير أسنان وصعوبة فتح الفم": "Teeth grinding and difficulty opening mouth",
    "حساسية زائدة للصوت أو اللمس": "Hypersensitivity to sound or touch",
    "حديث الولادة": "Newborn",
    "برودة الأطراف": "Cold extremities",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###

    conn = op.get_bind()
    symptoms = sa.table('symptoms', sa.column('id', sa.Integer), sa.column('name', sa.String),
                         sa.column('name_en', sa.String))
    for ar_name, en_name in _SYMPTOM_TRANSLATIONS.items():
        conn.execute(symptoms.update().where(symptoms.c.name == ar_name).values(name_en=en_name))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('symptoms', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
