"""add weaning_solid_feed_age_days and ram_breeding_season_window_days

Revision ID: 0e44e990d342
Revises: 7c612705393f
Create Date: 2026-08-20 21:00:16.439614

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e44e990d342'
down_revision = '7c612705393f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weaning_solid_feed_age_days', sa.Integer(), nullable=False, server_default='45'))
        batch_op.add_column(sa.Column('ram_breeding_season_window_days', sa.Integer(), nullable=False, server_default='60'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('ram_breeding_season_window_days')
        batch_op.drop_column('weaning_solid_feed_age_days')

    # ### end Alembic commands ###
