"""add optional box_count and box_quantity to pharmacy

Revision ID: 0f2a5b602937
Revises: 65f1ab7765d1
Create Date: 2026-08-31 07:24:02.383078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0f2a5b602937'
down_revision = '65f1ab7765d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('box_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('box_quantity', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('box_quantity')
        batch_op.drop_column('box_count')

    # ### end Alembic commands ###
