"""add last_alert_generators_run throttle field to farm_settings

Revision ID: 14fa742d05a4
Revises: 7b2f00784e16
Create Date: 2026-09-14 20:34:19.279205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '14fa742d05a4'
down_revision = '7b2f00784e16'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_alert_generators_run', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('last_alert_generators_run')

    # ### end Alembic commands ###
