"""add milk-specific withdrawal fields (pharmacy + vet_visits/diseases/vaccinations)

Revision ID: 1727f39bc929
Revises: 90153dab741b
Create Date: 2026-08-30 13:21:48.559366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1727f39bc929'
down_revision = '90153dab741b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_until_milk', sa.Date(), nullable=True))

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_days_milk', sa.Integer(), nullable=False, server_default='0'))

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_until_milk', sa.Date(), nullable=True))

    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.add_column(sa.Column('withdrawal_until_milk', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.drop_column('withdrawal_until_milk')

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_column('withdrawal_until_milk')

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('withdrawal_days_milk')

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('withdrawal_until_milk')

    # ### end Alembic commands ###
