"""add min_male_breeding_age_days

Revision ID: 1b8869de3ab5
Revises: 6f8387d9b5b3
Create Date: 2026-08-21 22:52:46.433928

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b8869de3ab5'
down_revision = '6f8387d9b5b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_male_breeding_age_days', sa.Integer(), nullable=False, server_default='180'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('min_male_breeding_age_days')

    # ### end Alembic commands ###
