"""add performance indexes on frequently joined FK and date columns

Revision ID: 1f60e9479bc4
Revises: 69a8410335a0
Create Date: 2026-08-11 04:47:56.518790

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1f60e9479bc4'
down_revision = '69a8410335a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animals_father_id'), ['father_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_animals_mother_id'), ['mother_id'], unique=False)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_log_created_at'), ['created_at'], unique=False)

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_diseases_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_finance_date'), ['date'], unique=False)
        batch_op.create_index(batch_op.f('ix_finance_related_animal_id'), ['related_animal_id'], unique=False)

    with op.batch_alter_table('matings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_matings_female_id'), ['female_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_matings_male_id'), ['male_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_assignee_id'), ['assignee_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tasks_due_date'), ['due_date'], unique=False)

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vaccinations_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vet_visits_animal_id'), ['animal_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vet_visits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vet_visits_animal_id'))

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vaccinations_animal_id'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_due_date'))
        batch_op.drop_index(batch_op.f('ix_tasks_assignee_id'))
        batch_op.drop_index(batch_op.f('ix_tasks_animal_id'))

    with op.batch_alter_table('matings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_matings_male_id'))
        batch_op.drop_index(batch_op.f('ix_matings_female_id'))

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_finance_related_animal_id'))
        batch_op.drop_index(batch_op.f('ix_finance_date'))

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_diseases_animal_id'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_log_created_at'))

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animals_mother_id'))
        batch_op.drop_index(batch_op.f('ix_animals_father_id'))

    # ### end Alembic commands ###
