"""add last_daily_tasks_auto_run to farm_settings

Revision ID: 21f955e9ff0c
Revises: 8d498eeeae80
Create Date: 2026-08-01 22:50:35.406279

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '21f955e9ff0c'
down_revision = '8d498eeeae80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_tasks_auto_run', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('last_daily_tasks_auto_run')

    # ### end Alembic commands ###
