"""add barn feeding schedules

Revision ID: 269f2855e512
Revises: e78394e319da
Create Date: 2026-08-06 21:28:59.217386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '269f2855e512'
down_revision = 'e78394e319da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('barn_feeding_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barn_id', sa.Integer(), nullable=False),
    sa.Column('meal_time', sa.Time(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barn_id'], ['barns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('barn_feeding_schedules')
    # ### end Alembic commands ###
