"""add isolation_started_at to animals

Revision ID: 2990a3925349
Revises: 269f2855e512
Create Date: 2026-08-08 00:40:21.921180

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2990a3925349'
down_revision = '269f2855e512'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('isolation_started_at', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('isolation_started_at')

    # ### end Alembic commands ###
