"""add weight_check_interval_days to farm_settings

Revision ID: 29f2056553a4
Revises: 2990a3925349
Create Date: 2026-08-08 01:35:30.982130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29f2056553a4'
down_revision = '2990a3925349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight_check_interval_days', sa.Integer(), nullable=False, server_default='30'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('weight_check_interval_days')

    # ### end Alembic commands ###
