"""add sales_lots and sales_lot_items

Revision ID: 2adfc2b52635
Revises: 063cb8138ee1
Create Date: 2026-08-11 21:40:15.712093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adfc2b52635'
down_revision = '063cb8138ee1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sales_lots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('target_amount', sa.Float(), nullable=True),
    sa.Column('share_token', sa.String(length=64), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('sales_lot_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['sales_lots.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('lot_id', 'animal_id', name='uq_sales_lot_animal')
    )
    with op.batch_alter_table('sales_lot_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sales_lot_items_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sales_lot_items_lot_id'), ['lot_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_lot_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sales_lot_items_lot_id'))
        batch_op.drop_index(batch_op.f('ix_sales_lot_items_animal_id'))

    op.drop_table('sales_lot_items')
    op.drop_table('sales_lots')
    # ### end Alembic commands ###
