"""add required and exclusionary fields to disease symptom link

Revision ID: 33bfa760a676
Revises: ebe5f88d7d08
Create Date: 2026-08-05 21:51:07.405720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33bfa760a676'
down_revision = 'ebe5f88d7d08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default صريح (بند إضافي 127) — الجدول عنده صفوف حقيقية
    # مبذورة أصلاً بالإنتاج (12 مرض × أعراضهم)؛ بدون قيمة افتراضية
    # بمستوى القاعدة نفسها، إضافة عمود NOT NULL على SQLite بجدول فيه
    # بيانات تفشل عند نسخ الصفوف القديمة.
    with op.batch_alter_table('disease_symptom_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_required', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('is_exclusionary', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_symptom_links', schema=None) as batch_op:
        batch_op.drop_column('is_exclusionary')
        batch_op.drop_column('is_required')

    # ### end Alembic commands ###
