"""add task sequencing (depends_on_task_id)

Revision ID: 34ff54f9f2bd
Revises: 012519904089
Create Date: 2026-07-23 06:07:00.123036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '34ff54f9f2bd'
down_revision = '012519904089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('depends_on_task_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_depends_on_task_id', 'tasks', ['depends_on_task_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_depends_on_task_id', type_='foreignkey')
        batch_op.drop_column('depends_on_task_id')

    # ### end Alembic commands ###
