"""assistant_draft_action

Revision ID: 3514102b6338
Revises: bdb1ac7b9f1e
Create Date: 2026-08-29 02:53:37.644159

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3514102b6338'
down_revision = 'bdb1ac7b9f1e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('assistant_draft_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_text', sa.Text(), nullable=False),
    sa.Column('input_source', sa.String(length=16), nullable=False),
    sa.Column('parsed_action_type', sa.String(length=64), nullable=True),
    sa.Column('parsed_payload_json', sa.Text(), nullable=True),
    sa.Column('summary_ar', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_by_id', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assistant_draft_actions')
    # ### end Alembic commands ###
