"""drop user specialty field (band 267 reverted per user request)

Revision ID: 36e1fb5acb68
Revises: fc4035f84b69
Create Date: 2026-08-27 08:36:25.188199

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36e1fb5acb68'
down_revision = 'fc4035f84b69'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.VARCHAR(length=80), nullable=True))

    # ### end Alembic commands ###
