"""add production cycle engine

Revision ID: 3a7718125863
Revises: 82158cf0b37b
Create Date: 2026-07-22 12:04:09.069370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a7718125863'
down_revision = '82158cf0b37b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cycle_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=32), nullable=False),
    sa.Column('stage_index', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=64), nullable=True),
    sa.Column('source_type', sa.String(length=32), nullable=True),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('cycle_status', sa.String(length=32), nullable=True),
    sa.Column('allowed_stage', sa.Integer(), nullable=True),
    sa.Column('completed_through', sa.Integer(), nullable=True),
    sa.Column('first_blocked_stage', sa.Integer(), nullable=True),
    sa.Column('next_required_step', sa.String(length=64), nullable=True),
    sa.Column('next_required_fix', sa.Text(), nullable=True),
    sa.Column('out_of_order_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('production_workflows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('route', sa.String(length=32), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=False),
    sa.Column('stage_name', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('destiny_decision', sa.String(length=32), nullable=True),
    sa.Column('missing_items', sa.Text(), nullable=True),
    sa.Column('out_of_order_count', sa.Integer(), nullable=False),
    sa.Column('target_sale_date', sa.Date(), nullable=True),
    sa.Column('target_profit_margin', sa.Float(), nullable=True),
    sa.Column('estimated_value', sa.Float(), nullable=True),
    sa.Column('weaning_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('purpose', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('purpose')

    op.drop_table('production_workflows')
    op.drop_table('cycle_events')
    # ### end Alembic commands ###
