"""add vat_number, sales_catalog_token, assets, asset_maintenance_logs, utility_readings

Revision ID: 425821f5c789
Revises: 1f60e9479bc4
Create Date: 2026-08-11 15:38:49.694247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '425821f5c789'
down_revision = '1f60e9479bc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utility_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('utility_type', sa.String(length=16), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(length=16), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('barn_id', sa.Integer(), nullable=True),
    sa.Column('maintenance_interval_days', sa.Integer(), nullable=True),
    sa.Column('last_maintenance_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barn_id'], ['barns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asset_maintenance_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('performed_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.ForeignKeyConstraint(['performed_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vat_number', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('sales_catalog_token', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('sales_catalog_token')
        batch_op.drop_column('vat_number')

    op.drop_table('asset_maintenance_logs')
    op.drop_table('assets')
    op.drop_table('utility_readings')
    # ### end Alembic commands ###
