"""add feed intelligence module

Revision ID: 426ac24ff8e0
Revises: e89d6f4304cb
Create Date: 2026-07-22 15:05:41.647643

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '426ac24ff8e0'
down_revision = 'e89d6f4304cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_rations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('purpose', sa.String(length=32), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feeds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('protein_percent', sa.Float(), nullable=True),
    sa.Column('energy_kcal_per_kg', sa.Float(), nullable=True),
    sa.Column('fiber_percent', sa.Float(), nullable=True),
    sa.Column('calcium_percent', sa.Float(), nullable=True),
    sa.Column('phosphorus_percent', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=32), nullable=True),
    sa.Column('unit_price', sa.Float(), nullable=True),
    sa.Column('available_qty', sa.Float(), nullable=True),
    sa.Column('min_stock_qty', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_ration_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ration_id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.ForeignKeyConstraint(['ration_id'], ['feed_rations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_barn_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('barn_id', sa.Integer(), nullable=False),
    sa.Column('ration_id', sa.Integer(), nullable=False),
    sa.Column('daily_qty_per_animal_kg', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barn_id'], ['barns.id'], ),
    sa.ForeignKeyConstraint(['ration_id'], ['feed_rations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feed_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=16), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('before_qty', sa.Float(), nullable=True),
    sa.Column('after_qty', sa.Float(), nullable=True),
    sa.Column('barn_id', sa.Integer(), nullable=True),
    sa.Column('animal_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['barn_id'], ['barns.id'], ),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feed_movements')
    op.drop_table('feed_barn_plans')
    op.drop_table('feed_ration_items')
    op.drop_table('feeds')
    op.drop_table('feed_rations')
    # ### end Alembic commands ###
