"""add treatment protocol templates

Revision ID: 42c400b98525
Revises: 50515ae9fd80
Create Date: 2026-07-25 13:11:54.992509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '42c400b98525'
down_revision = '50515ae9fd80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('treatment_protocols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('disease_type_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['disease_type_id'], ['disease_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('treatment_protocol_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('day_offset', sa.Integer(), nullable=False),
    sa.Column('step_title', sa.String(length=160), nullable=False),
    sa.Column('pharmacy_id', sa.Integer(), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('treatment_kind', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['pharmacy_id'], ['pharmacy.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['treatment_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('protocol_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol_id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('applied_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['applied_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['protocol_id'], ['treatment_protocols.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('protocol_applications')
    op.drop_table('treatment_protocol_steps')
    op.drop_table('treatment_protocols')
    # ### end Alembic commands ###
