"""add birth record checklist

Revision ID: 4801c979baf9
Revises: b7982796bf61
Create Date: 2026-07-22 20:35:18.067741

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4801c979baf9'
down_revision = 'b7982796bf61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birth_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('animal_id', sa.Integer(), nullable=False),
    sa.Column('breathing_ok', sa.Boolean(), nullable=True),
    sa.Column('standing_ok', sa.Boolean(), nullable=True),
    sa.Column('colostrum_received', sa.Boolean(), nullable=True),
    sa.Column('cord_treated', sa.Boolean(), nullable=True),
    sa.Column('birth_defects', sa.Text(), nullable=True),
    sa.Column('recorded_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('animal_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birth_records')
    # ### end Alembic commands ###
