"""add checklist rationale and doctor directory fields

Revision ID: 4a7841956b0d
Revises: 5bd30a7ee32e
Create Date: 2026-08-11 03:08:24.714874

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a7841956b0d'
down_revision = '5bd30a7ee32e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rationale', sa.Text(), nullable=True))

    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_external', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('clinic_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('area', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('doctors', schema=None) as batch_op:
        batch_op.drop_column('notes')
        batch_op.drop_column('area')
        batch_op.drop_column('clinic_name')
        batch_op.drop_column('is_external')

    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_column('rationale')

    # ### end Alembic commands ###
