"""add smart sale engine settings and female sale flags

Revision ID: 4f12fc0b1aa1
Revises: 8dc69dbde2f9
Create Date: 2026-07-23 05:49:36.471922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f12fc0b1aa1'
down_revision = '8dc69dbde2f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('refuses_nursing', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('udder_damaged', sa.Boolean(), nullable=True))

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_profit_margin_percent', sa.Float(), nullable=False, server_default='30.0'))
        batch_op.add_column(sa.Column('regular_sale_age_days', sa.Integer(), nullable=False, server_default='180'))
        batch_op.add_column(sa.Column('udhiyah_min_age_days', sa.Integer(), nullable=False, server_default='195'))
        batch_op.add_column(sa.Column('female_delayed_conception_days', sa.Integer(), nullable=False, server_default='60'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('female_delayed_conception_days')
        batch_op.drop_column('udhiyah_min_age_days')
        batch_op.drop_column('regular_sale_age_days')
        batch_op.drop_column('target_profit_margin_percent')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('udder_damaged')
        batch_op.drop_column('refuses_nursing')

    # ### end Alembic commands ###
