"""add breed, feed_class, copper flags, pregnancy outcome, rules engine settings

Revision ID: 50515ae9fd80
Revises: ea181a74cbd0
Create Date: 2026-07-25 11:03:30.181683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '50515ae9fd80'
down_revision = 'ea181a74cbd0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('breed', sa.String(length=40), nullable=True, server_default='عام/غير محدد'))

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('concentrate_increase_max_percent_weekly', sa.Float(), nullable=False, server_default='10.0'))
        batch_op.add_column(sa.Column('concentrate_increase_window_days', sa.Integer(), nullable=False, server_default='7'))
        batch_op.add_column(sa.Column('ca_phosphorus_target_ratio', sa.Float(), nullable=False, server_default='2.0'))
        batch_op.add_column(sa.Column('ca_phosphorus_tolerance', sa.Float(), nullable=False, server_default='0.5'))
        batch_op.add_column(sa.Column('abortion_barn_monitor_days', sa.Integer(), nullable=False, server_default='14'))

    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('feed_class', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('contains_high_copper', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('contains_high_copper', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('outcome', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('outcome_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('outcome_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.drop_column('outcome_notes')
        batch_op.drop_column('outcome_date')
        batch_op.drop_column('outcome')

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('contains_high_copper')

    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('contains_high_copper')
        batch_op.drop_column('feed_class')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('abortion_barn_monitor_days')
        batch_op.drop_column('ca_phosphorus_tolerance')
        batch_op.drop_column('ca_phosphorus_target_ratio')
        batch_op.drop_column('concentrate_increase_window_days')
        batch_op.drop_column('concentrate_increase_max_percent_weekly')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('breed')

    # ### end Alembic commands ###
