"""add permissions_customized flag to roles

Revision ID: 5244dce3cc23
Revises: 1727f39bc929
Create Date: 2026-08-31 00:38:51.938727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5244dce3cc23'
down_revision = '1727f39bc929'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('permissions_customized', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column('permissions_customized')

    # ### end Alembic commands ###
