"""add cycle engine age thresholds to farm_settings

Revision ID: 53536ae05ec9
Revises: 16b2c9624d5f
Create Date: 2026-08-08 15:26:06.904093

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53536ae05ec9'
down_revision = '16b2c9624d5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('newborn_route_max_age_days', sa.Integer(), nullable=False, server_default='120'))
        batch_op.add_column(sa.Column('male_fertility_exam_alt_age_days', sa.Integer(), nullable=False, server_default='180'))
        batch_op.add_column(sa.Column('weaning_min_age_days', sa.Integer(), nullable=False, server_default='60'))
        batch_op.add_column(sa.Column('weaning_alt_age_days', sa.Integer(), nullable=False, server_default='90'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('weaning_alt_age_days')
        batch_op.drop_column('weaning_min_age_days')
        batch_op.drop_column('male_fertility_exam_alt_age_days')
        batch_op.drop_column('newborn_route_max_age_days')

    # ### end Alembic commands ###
