"""equipment needs_maintenance + movement condition/no_return_expected fields

Revision ID: 542d86d8464e
Revises: 36e1fb5acb68
Create Date: 2026-08-27 19:58:40.453682

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '542d86d8464e'
down_revision = '36e1fb5acb68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('needs_maintenance', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('equipment_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('no_return_expected', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('condition_at_handout', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('condition_at_return', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_movements', schema=None) as batch_op:
        batch_op.drop_column('condition_at_return')
        batch_op.drop_column('condition_at_handout')
        batch_op.drop_column('no_return_expected')

    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.drop_column('needs_maintenance')

    # ### end Alembic commands ###
