"""add inventory_counts table

Revision ID: 55bc25434c90
Revises: 689c8d69b22e
Create Date: 2026-08-17 04:14:02.944611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55bc25434c90'
down_revision = '689c8d69b22e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory_counts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('item_name', sa.String(length=160), nullable=False),
    sa.Column('count_date', sa.Date(), nullable=False),
    sa.Column('expected_qty', sa.Float(), nullable=False),
    sa.Column('actual_qty', sa.Float(), nullable=False),
    sa.Column('diff_qty', sa.Float(), nullable=False),
    sa.Column('diff_value', sa.Float(), nullable=True),
    sa.Column('finance_id', sa.Integer(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_id'], ['finance.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory_counts')
    # ### end Alembic commands ###
