"""add per-worker sponsor identity fields

Revision ID: 5e5d75b5e657
Revises: abd2909c7fbd
Create Date: 2026-09-07 14:45:58.406418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e5d75b5e657'
down_revision = 'abd2909c7fbd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sponsor_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('sponsor_national_id', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('sponsor_phone', sa.String(length=32), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('sponsor_phone')
        batch_op.drop_column('sponsor_national_id')
        batch_op.drop_column('sponsor_name')

    # ### end Alembic commands ###
