"""add worker identity fields and owner_national_id

Revision ID: 5e8a9af3b801
Revises: ea7ca77f3f10
Create Date: 2026-08-26 20:35:34.156129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e8a9af3b801'
down_revision = 'ea7ca77f3f10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('owner_national_id', sa.String(length=30), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nationality', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('passport_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('border_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('payment_method')
        batch_op.drop_column('border_number')
        batch_op.drop_column('passport_number')
        batch_op.drop_column('nationality')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('owner_national_id')

    # ### end Alembic commands ###
