"""add last_daily_telegram_report_sent

Revision ID: 614a8e4820bb
Revises: 65b2ccc2a3af
Create Date: 2026-08-26 09:24:32.327560

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614a8e4820bb'
down_revision = '65b2ccc2a3af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_telegram_report_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('last_daily_telegram_report_sent')

    # ### end Alembic commands ###
