"""add symptom decision tree and pharmacy min_stock_qty

Revision ID: 634a174c9f1c
Revises: f4365b27d099
Create Date: 2026-07-24 18:22:21.270113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '634a174c9f1c'
down_revision = 'f4365b27d099'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('disease_symptom_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('disease_type_id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['disease_type_id'], ['disease_types.id'], ),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('disease_type_id', 'symptom_id', name='uq_disease_symptom')
    )
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_stock_qty', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('min_stock_qty')

    op.drop_table('disease_symptom_links')
    op.drop_table('symptoms')
    # ### end Alembic commands ###
