"""assistant_message_image_url

Revision ID: 645ab1b2f181
Revises: 3514102b6338
Create Date: 2026-08-29 04:59:42.242085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '645ab1b2f181'
down_revision = '3514102b6338'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_messages', schema=None) as batch_op:
        batch_op.drop_column('image_url')

    # ### end Alembic commands ###
