"""add User.ui_level

Revision ID: 6583ca3e8b81
Revises: 0e44e990d342
Create Date: 2026-08-21 02:06:02.056753

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6583ca3e8b81'
down_revision = '0e44e990d342'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ui_level', sa.String(length=8), nullable=False, server_default='normal'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('ui_level')

    # ### end Alembic commands ###
