"""add predictive stock alert setting

Revision ID: 65b2ccc2a3af
Revises: e3bebbcda118
Create Date: 2026-08-26 09:06:18.229168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65b2ccc2a3af'
down_revision = 'e3bebbcda118'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('predictive_stock_alert_days', sa.Integer(), nullable=False, server_default='7'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('predictive_stock_alert_days')

    # ### end Alembic commands ###
