"""add missing indexes on animal_weights.animal_id, animal_notes.animal_id, milk_records.animal_id, tasks.barn_id

Revision ID: 65e126c24a42
Revises: 0f2a5b602937
Create Date: 2026-09-06 22:49:12.474413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65e126c24a42'
down_revision = '0f2a5b602937'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_notes_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('animal_weights', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_animal_weights_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('milk_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_milk_records_animal_id'), ['animal_id'], unique=False)

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tasks_barn_id'), ['barn_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tasks_barn_id'))

    with op.batch_alter_table('milk_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_milk_records_animal_id'))

    with op.batch_alter_table('animal_weights', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_weights_animal_id'))

    with op.batch_alter_table('animal_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_animal_notes_animal_id'))

    # ### end Alembic commands ###
