"""add optional english names to breed, animal color, disease type

Revision ID: 65f1ab7765d1
Revises: 2c5eade49331
Create Date: 2026-08-31 06:41:20.448184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65f1ab7765d1'
down_revision = '2c5eade49331'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_colors', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=60), nullable=True))

    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=60), nullable=True))

    with op.batch_alter_table('disease_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=160), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_types', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    with op.batch_alter_table('animal_colors', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    # ### end Alembic commands ###
