"""add animal market trip fields

Revision ID: 689c8d69b22e
Revises: 801b44a122b6
Create Date: 2026-08-16 20:57:37.047571

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '689c8d69b22e'
down_revision = '801b44a122b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('market_trip_started_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('market_trip_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('market_trip_note')
        batch_op.drop_column('market_trip_started_at')

    # ### end Alembic commands ###
