"""add breed care_notes

Revision ID: 69a8410335a0
Revises: 4a7841956b0d
Create Date: 2026-08-11 03:34:29.157944

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69a8410335a0'
down_revision = '4a7841956b0d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('care_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('breeds', schema=None) as batch_op:
        batch_op.drop_column('care_notes')

    # ### end Alembic commands ###
