"""add task quality rating fields

Revision ID: 6f8387d9b5b3
Revises: 6583ca3e8b81
Create Date: 2026-08-21 21:05:14.624104

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f8387d9b5b3'
down_revision = '6583ca3e8b81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quality_rating', sa.String(length=16), nullable=True))
        batch_op.add_column(sa.Column('quality_rating_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('quality_rated_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('quality_rated_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_quality_rated_by_id_users', 'users', ['quality_rated_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_quality_rated_by_id_users', type_='foreignkey')
        batch_op.drop_column('quality_rated_at')
        batch_op.drop_column('quality_rated_by_id')
        batch_op.drop_column('quality_rating_note')
        batch_op.drop_column('quality_rating')

    # ### end Alembic commands ###
