"""add indexes to reports table for performance

Revision ID: 7b2f00784e16
Revises: 943e8b33be80
Create Date: 2026-09-14 20:21:57.503479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b2f00784e16'
down_revision = '943e8b33be80'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_reports_animal_id'), ['animal_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_barn_id'), ['barn_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_executor_id'), ['executor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_manager_id'), ['manager_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_reports_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_reports_status'))
        batch_op.drop_index(batch_op.f('ix_reports_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_reports_manager_id'))
        batch_op.drop_index(batch_op.f('ix_reports_executor_id'))
        batch_op.drop_index(batch_op.f('ix_reports_barn_id'))
        batch_op.drop_index(batch_op.f('ix_reports_animal_id'))

    # ### end Alembic commands ###
