"""add vaccination schedule target animal ids

Revision ID: 7c612705393f
Revises: 8bd06b904336
Create Date: 2026-08-17 23:45:15.012002

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7c612705393f'
down_revision = '8bd06b904336'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_schedules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_animal_ids', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccination_schedules', schema=None) as batch_op:
        batch_op.drop_column('target_animal_ids')

    # ### end Alembic commands ###
