"""add feed unit_weight_kg and bale unit option

Revision ID: 801b44a122b6
Revises: a71d1d4e36ae
Create Date: 2026-08-16 09:05:58.907504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '801b44a122b6'
down_revision = 'a71d1d4e36ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_weight_kg', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('unit_weight_kg')

    # ### end Alembic commands ###
