"""add reproduction module

Revision ID: 82158cf0b37b
Revises: a5d36df4daa6
Create Date: 2026-07-22 10:46:25.333221

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '82158cf0b37b'
down_revision = 'a5d36df4daa6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('male_id', sa.Integer(), nullable=True),
    sa.Column('male_note', sa.String(length=160), nullable=True),
    sa.Column('barn_id', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['barn_id'], ['barns.id'], ),
    sa.ForeignKeyConstraint(['female_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['male_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twin_estrus_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ewe_id', sa.Integer(), nullable=False),
    sa.Column('protocol_name', sa.String(length=160), nullable=True),
    sa.Column('supervising_doctor_id', sa.Integer(), nullable=True),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('ram_note', sa.String(length=160), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('device_insert_planned_at', sa.Date(), nullable=True),
    sa.Column('device_remove_planned_at', sa.Date(), nullable=True),
    sa.Column('expected_estrus_start', sa.Date(), nullable=True),
    sa.Column('expected_estrus_end', sa.Date(), nullable=True),
    sa.Column('mating_window_start', sa.Date(), nullable=True),
    sa.Column('mating_window_end', sa.Date(), nullable=True),
    sa.Column('confirmed_mating_date', sa.Date(), nullable=True),
    sa.Column('pregnancy_check_date', sa.Date(), nullable=True),
    sa.Column('embryo_count_start', sa.Integer(), nullable=True),
    sa.Column('embryo_count_end', sa.Integer(), nullable=True),
    sa.Column('expected_birth_date', sa.Date(), nullable=True),
    sa.Column('eligibility_status', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['ewe_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['supervising_doctor_id'], ['doctors.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hormone_injections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('hormone_name', sa.String(length=120), nullable=False),
    sa.Column('dose_value', sa.Float(), nullable=True),
    sa.Column('dose_unit', sa.String(length=32), nullable=True),
    sa.Column('route', sa.String(length=32), nullable=True),
    sa.Column('planned_at', sa.Date(), nullable=True),
    sa.Column('actual_at', sa.Date(), nullable=True),
    sa.Column('given_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['twin_estrus_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pregnancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('female_id', sa.Integer(), nullable=False),
    sa.Column('mating_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('confirmed', sa.Boolean(), nullable=False),
    sa.Column('sonar_date', sa.Date(), nullable=True),
    sa.Column('embryo_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['female_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['mating_id'], ['matings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('repro_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('device_type', sa.String(length=120), nullable=False),
    sa.Column('trade_name', sa.String(length=120), nullable=True),
    sa.Column('inserted_at', sa.Date(), nullable=False),
    sa.Column('inserted_by', sa.String(length=120), nullable=True),
    sa.Column('planned_remove_at', sa.Date(), nullable=True),
    sa.Column('actual_remove_at', sa.Date(), nullable=True),
    sa.Column('early_loss', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['twin_estrus_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sonar_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.Column('ewe_id', sa.Integer(), nullable=False),
    sa.Column('exam_date', sa.Date(), nullable=False),
    sa.Column('gestation_age_days', sa.Integer(), nullable=True),
    sa.Column('result', sa.String(length=32), nullable=True),
    sa.Column('embryo_count', sa.Integer(), nullable=True),
    sa.Column('heartbeat', sa.Boolean(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.Column('recheck_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ),
    sa.ForeignKeyConstraint(['ewe_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['twin_estrus_programs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('twin_estrus_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=False),
    sa.Column('mating_date', sa.Date(), nullable=False),
    sa.Column('ram_id', sa.Integer(), nullable=True),
    sa.Column('ram_note', sa.String(length=160), nullable=True),
    sa.Column('confirmation_status', sa.String(length=32), nullable=True),
    sa.Column('observed_by', sa.String(length=120), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['program_id'], ['twin_estrus_programs.id'], ),
    sa.ForeignKeyConstraint(['ram_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('twin_estrus_attempts')
    op.drop_table('sonar_results')
    op.drop_table('repro_devices')
    op.drop_table('pregnancies')
    op.drop_table('hormone_injections')
    op.drop_table('twin_estrus_programs')
    op.drop_table('matings')
    # ### end Alembic commands ###
