"""add email to users and last_daily_email_report_sent to farm_settings

Revision ID: 8260d1ea17b7
Revises: 84150f1512a3
Create Date: 2026-08-08 22:56:00.444761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8260d1ea17b7'
down_revision = '84150f1512a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_email_report_sent', sa.Date(), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('email')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('last_daily_email_report_sent')

    # ### end Alembic commands ###
