"""add processed_telegram_updates table

Revision ID: 84150f1512a3
Revises: 863346534955
Create Date: 2026-08-08 22:28:23.904768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84150f1512a3'
down_revision = '863346534955'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processed_telegram_updates',
    sa.Column('update_id', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('update_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processed_telegram_updates')
    # ### end Alembic commands ###
