"""add equipment borrow return tracking

Revision ID: 8512690b165c
Revises: 3d5345e759ea
Create Date: 2026-08-03 14:07:49.194071

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8512690b165c'
down_revision = '3d5345e759ea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_movements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('borrowed_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('returned_at', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_equipment_movements_borrowed_by_id', 'users', ['borrowed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_movements', schema=None) as batch_op:
        batch_op.drop_constraint('fk_equipment_movements_borrowed_by_id', type_='foreignkey')
        batch_op.drop_column('returned_at')
        batch_op.drop_column('borrowed_by_id')

    # ### end Alembic commands ###
