"""add theme preference to users

Revision ID: 863346534955
Revises: 0251d60fc028
Create Date: 2026-08-08 20:37:48.686758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '863346534955'
down_revision = '0251d60fc028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('theme', sa.String(length=8), nullable=False, server_default='light'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('theme')

    # ### end Alembic commands ###
