"""add employee_of_month recipient_name

Revision ID: 8757a4a3ed0c
Revises: e782517cf451
Create Date: 2026-08-26 11:14:17.788748

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8757a4a3ed0c'
down_revision = 'e782517cf451'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_of_month', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_name', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('employee_of_month', schema=None) as batch_op:
        batch_op.drop_column('recipient_name')

    # ### end Alembic commands ###
