"""add workflow stall alert days setting

Revision ID: 8bd06b904336
Revises: 55bc25434c90
Create Date: 2026-08-17 20:18:22.991271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bd06b904336'
down_revision = '55bc25434c90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('workflow_stall_alert_days', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('workflow_stall_alert_days')

    # ### end Alembic commands ###
