"""add invoice fields to finance and farm identity to farm_settings

Revision ID: 8d498eeeae80
Revises: b8c9d0e1f2a3
Create Date: 2026-07-31 15:38:05.413951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d498eeeae80'
down_revision = 'b8c9d0e1f2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_name', sa.String(length=160), nullable=True))
        batch_op.add_column(sa.Column('farm_phone', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('farm_address', sa.String(length=255), nullable=True))

    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_number', sa.String(length=40), nullable=True))
        batch_op.add_column(sa.Column('invoice_issued_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('invoice_file_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('no_invoice', sa.Boolean(), nullable=False, server_default=sa.false()))
        batch_op.add_column(sa.Column('buyer_name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('buyer_phone', sa.String(length=30), nullable=True))
        batch_op.create_unique_constraint('uq_finance_invoice_number', ['invoice_number'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_constraint('uq_finance_invoice_number', type_='unique')
        batch_op.drop_column('buyer_phone')
        batch_op.drop_column('buyer_name')
        batch_op.drop_column('no_invoice')
        batch_op.drop_column('invoice_file_url')
        batch_op.drop_column('invoice_issued_at')
        batch_op.drop_column('invoice_number')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('farm_address')
        batch_op.drop_column('farm_phone')
        batch_op.drop_column('farm_name')

    # ### end Alembic commands ###
