"""assistant_draft_action_audio_url

Revision ID: 90153dab741b
Revises: 645ab1b2f181
Create Date: 2026-08-29 10:33:56.121602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90153dab741b'
down_revision = '645ab1b2f181'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_draft_actions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('audio_url', sa.String(length=500), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assistant_draft_actions', schema=None) as batch_op:
        batch_op.drop_column('audio_url')

    # ### end Alembic commands ###
