"""add last_daily_push_report_sent to farm_settings

Revision ID: 943e8b33be80
Revises: e3b100509865
Create Date: 2026-09-14 09:06:12.947773

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '943e8b33be80'
down_revision = 'e3b100509865'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_daily_push_report_sent', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('last_daily_push_report_sent')

    # ### end Alembic commands ###
