"""add finance_id to asset_maintenance_logs and utility_readings (band 263)

Revision ID: 9444d4ca253d
Revises: 0228f14ddc52
Create Date: 2026-08-27 03:05:21.889129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9444d4ca253d'
down_revision = '0228f14ddc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset_maintenance_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_asset_maintenance_logs_finance_id_finance', 'finance', ['finance_id'], ['id'])

    with op.batch_alter_table('utility_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('finance_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_utility_readings_finance_id_finance', 'finance', ['finance_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('utility_readings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_utility_readings_finance_id_finance', type_='foreignkey')
        batch_op.drop_column('finance_id')

    with op.batch_alter_table('asset_maintenance_logs', schema=None) as batch_op:
        batch_op.drop_constraint('fk_asset_maintenance_logs_finance_id_finance', type_='foreignkey')
        batch_op.drop_column('finance_id')

    # ### end Alembic commands ###
