"""task due_time + task_late_grace_minutes setting (band 278)

Revision ID: 955f13951cc4
Revises: 542d86d8464e
Create Date: 2026-08-28 01:10:59.530459

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '955f13951cc4'
down_revision = '542d86d8464e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('task_late_grace_minutes', sa.Integer(), nullable=False, server_default='60'))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_time', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('due_time')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('task_late_grace_minutes')

    # ### end Alembic commands ###
