"""add equipment photo_url

Revision ID: 96d1ccfef967
Revises: 2adfc2b52635
Create Date: 2026-08-12 03:00:21.803272

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '96d1ccfef967'
down_revision = '2adfc2b52635'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('photo_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('equipment_items', schema=None) as batch_op:
        batch_op.drop_column('photo_url')

    # ### end Alembic commands ###
