"""add name_en/text_en to report_types and checkup_item_presets

Revision ID: a1c2d3e4f5a6
Revises: 0b8f5e2ebf87
Create Date: 2026-09-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1c2d3e4f5a6'
down_revision = '0b8f5e2ebf87'
branch_labels = None
depends_on = None


# بند إصلاح (فحص عميق — طلبك: "تأكد من باقي الشاشات ما فيهم نفس
# المشكلة" بعد بلاغ أعراض المساعد التشخيصي) — نفس فجوة الترجمة على
# شاشتين إضافيتين: "نوع البلاغ" (report_types) و"بنود الفحص"
# (checkup_item_presets). بذور إنجليزية لكل القيم الافتراضية المزروعة
# أصلاً بأي مزرعة شغّالة، عشان تلقط الترجمة فوراً بمجرد الترقية.
_REPORT_TYPE_TRANSLATIONS = {
    "مرض": "Disease",
    "مشكلة": "Problem",
    "صيانة": "Maintenance",
    "أخرى": "Other",
}

_CHECKUP_ITEM_TRANSLATIONS = {
    "فحص الحرارة والنبض": "Temperature & pulse check",
    "فحص الجلد والصوف (طفيليات خارجية)": "Skin & wool check (external parasites)",
    "فحص العين والأنف": "Eye & nose check",
    "فحص الخف/الحافر": "Hoof check",
    "فحص الخراجات أو الكتل الظاهرة": "Abscess / visible lump check",
    "فحص الشهية والحالة العامة": "Appetite & general condition check",
    "رفع تقرير حالة الرأس": "Submit head status report",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('report_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=60), nullable=True))
    with op.batch_alter_table('checkup_item_presets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('text_en', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###

    conn = op.get_bind()
    report_types = sa.table('report_types', sa.column('id', sa.Integer), sa.column('name', sa.String),
                             sa.column('name_en', sa.String))
    for ar_name, en_name in _REPORT_TYPE_TRANSLATIONS.items():
        conn.execute(report_types.update().where(report_types.c.name == ar_name).values(name_en=en_name))

    checkup_items = sa.table('checkup_item_presets', sa.column('id', sa.Integer), sa.column('text', sa.String),
                              sa.column('text_en', sa.String))
    for ar_text, en_text in _CHECKUP_ITEM_TRANSLATIONS.items():
        conn.execute(checkup_items.update().where(checkup_items.c.text == ar_text).values(text_en=en_text))


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checkup_item_presets', schema=None) as batch_op:
        batch_op.drop_column('text_en')
    with op.batch_alter_table('report_types', schema=None) as batch_op:
        batch_op.drop_column('name_en')
    # ### end Alembic commands ###
