"""add pharmacy unit_price, disease quantity_used, vaccination quantity_used and cost

Revision ID: a8cabddedf0c
Revises: bed816c13bb5
Create Date: 2026-07-23 18:20:05.801609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8cabddedf0c'
down_revision = 'bed816c13bb5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_used', sa.Float(), nullable=True))

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price', sa.Float(), nullable=True))

    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity_used', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('cost', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vaccinations', schema=None) as batch_op:
        batch_op.drop_column('cost')
        batch_op.drop_column('quantity_used')

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('unit_price')

    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_column('quantity_used')

    # ### end Alembic commands ###
