"""add daily_reports table

Revision ID: aaad8319e0f3
Revises: 5e5d75b5e657
Create Date: 2026-09-08 10:44:09.034481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaad8319e0f3'
down_revision = '5e5d75b5e657'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('author_text', sa.Text(), nullable=False),
    sa.Column('author_lang', sa.String(length=8), nullable=False),
    sa.Column('arabic_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('author_id', 'report_date', name='uq_daily_report_author_date')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('daily_reports')
    # ### end Alembic commands ###
