"""add low_stock_alert_sent to feeds and pharmacy

Revision ID: abd2909c7fbd
Revises: 65e126c24a42
Create Date: 2026-09-07 01:24:43.557582

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'abd2909c7fbd'
down_revision = '65e126c24a42'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_alert_sent', sa.Boolean(), nullable=False, server_default=sa.false()))

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('low_stock_alert_sent', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('low_stock_alert_sent')

    with op.batch_alter_table('feeds', schema=None) as batch_op:
        batch_op.drop_column('low_stock_alert_sent')

    # ### end Alembic commands ###
