"""add title_en/description_en/rationale_en to checklist_items

Revision ID: b2d3e4f5a6b7
Revises: a1c2d3e4f5a6
Create Date: 2026-09-08 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2d3e4f5a6b7'
down_revision = 'a1c2d3e4f5a6'
branch_labels = None
depends_on = None


# بند إصلاح (فحص عميق — طلبك: "كلهم نفس المشكله ... حل مشكلة التعريب")
# — دليل المربي المبتدئ («خطوات أولى موصى بها» بشاشة الترحيب/الرئيسية)
# ما كان له أي ترجمة إطلاقاً. الأعمدة تُعبّى فوراً بعد النشر عبر
# `release: flask db upgrade && flask seed` (Procfile) — `seed()` يحدّث
# نصوص `ChecklistItem` الموجودة idempotent (`app/cli.py`)، فما نحتاج
# نكرّر بيانات الترجمة هنا براو SQL زيادة.


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=220), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('rationale_en', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('checklist_items', schema=None) as batch_op:
        batch_op.drop_column('rationale_en')
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')
    # ### end Alembic commands ###
