"""drop employee_of_month table

Revision ID: b796380264b0
Revises: 5e8a9af3b801
Create Date: 2026-08-26 22:25:42.062105

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b796380264b0'
down_revision = '5e8a9af3b801'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('employee_of_month')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('employee_of_month',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('year', sa.INTEGER(), nullable=False),
    sa.Column('month', sa.INTEGER(), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('score', sa.FLOAT(), nullable=False),
    sa.Column('status', sa.VARCHAR(length=24), nullable=False),
    sa.Column('bonus_amount', sa.FLOAT(), nullable=True),
    sa.Column('finance_id', sa.INTEGER(), nullable=True),
    sa.Column('confirmed_by_id', sa.INTEGER(), nullable=True),
    sa.Column('confirmed_at', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=True),
    sa.Column('recipient_name', sa.VARCHAR(length=120), nullable=True),
    sa.ForeignKeyConstraint(['confirmed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['finance_id'], ['finance.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('year', 'month', name=op.f('uq_employee_of_month_period'))
    )
    # ### end Alembic commands ###
