"""add mother breeding readiness settings

Revision ID: b7982796bf61
Revises: 32671e91dbd1
Create Date: 2026-07-22 20:23:48.715260

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b7982796bf61'
down_revision = '32671e91dbd1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_breeding_age_days', sa.Integer(), nullable=False, server_default='240'))
        batch_op.add_column(sa.Column('min_rest_after_birth_days', sa.Integer(), nullable=False, server_default='60'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('min_rest_after_birth_days')
        batch_op.drop_column('min_breeding_age_days')

    # ### end Alembic commands ###
