"""add settlement_pledge_text to farm_settings

Revision ID: ba252cc27ead
Revises: b95dbf33a91f
Create Date: 2026-09-12 03:19:31.513491

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ba252cc27ead'
down_revision = 'b95dbf33a91f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('settlement_pledge_text', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('settlement_pledge_text')

    # ### end Alembic commands ###
