"""add disease_types table and pharmacy usage/dosage fields

Revision ID: bed816c13bb5
Revises: 3b14898d3db1
Create Date: 2026-07-23 16:47:47.622640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bed816c13bb5'
down_revision = '3b14898d3db1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('disease_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_method', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('standard_dosage_note', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('standard_dosage_note')
        batch_op.drop_column('usage_method')

    op.drop_table('disease_types')
    # ### end Alembic commands ###
