"""add setup checklist dismissed flag

Revision ID: c00c097d189a
Revises: fb07a9e73dfa
Create Date: 2026-07-27 16:29:37.562752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00c097d189a'
down_revision = 'fb07a9e73dfa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('setup_checklist_dismissed', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('setup_checklist_dismissed')

    # ### end Alembic commands ###
