"""add saudi_arrival_date and worker_travel_periods (band 247)

Revision ID: c22a228b9094
Revises: b796380264b0
Create Date: 2026-08-26 23:15:09.188827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c22a228b9094'
down_revision = 'b796380264b0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker_travel_periods',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('worker_travel_periods', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_travel_periods_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saudi_arrival_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('saudi_arrival_date')

    with op.batch_alter_table('worker_travel_periods', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_travel_periods_user_id'))

    op.drop_table('worker_travel_periods')
    # ### end Alembic commands ###
