"""add title_key to tasks

Revision ID: c3e4f5a6b7c8
Revises: b2d3e4f5a6b7
Create Date: 2026-09-09 00:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e4f5a6b7c8'
down_revision = 'b2d3e4f5a6b7'
branch_labels = None
depends_on = None


# بند إصلاح (فحص عميق — طلبك: "افحص جميع النوافذ بعمق") — عناوين
# المهام اليومية التلقائية الأربعة الثابتة (`daily_task_service.py`)
# كانت تُخزَّن عربي بحت وقت الإنشاء وتبقى مجمَّدة كذلك للأبد. بذور
# `title_key` للمهام الموجودة أصلاً بقاعدة البيانات (لو فيها) حسب
# `source_type='DailyHusbandry'` و`title` المطابق — أي مهمة قديمة
# بعنوان غير مطابق (نص حر من `DailyTaskTemplate`) تبقى `title_key=NULL`
# كما هي، بلا أي تغيير بسلوكها.
_TITLE_TO_KEY = {
    "🚧 مراجعة العزل والحجر": "daily_isolation_review",
    "🍼 متابعة المواليد والرضاعة": "daily_newborn_review",
    "⚖️ مراجعة الفطام والفرز": "daily_weaning_review",
    "💊 مراجعة الحالات المرضية المفتوحة": "daily_withdrawal_review",
}


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_key', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###

    conn = op.get_bind()
    tasks = sa.table('tasks', sa.column('id', sa.Integer), sa.column('title', sa.String),
                      sa.column('source_type', sa.String), sa.column('title_key', sa.String))
    for title, key in _TITLE_TO_KEY.items():
        conn.execute(
            tasks.update()
            .where(tasks.c.source_type == 'DailyHusbandry', tasks.c.title == title)
            .values(title_key=key)
        )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_column('title_key')
    # ### end Alembic commands ###
