"""add disease closing fields

Revision ID: c4e36a948301
Revises: 426ac24ff8e0
Create Date: 2026-07-22 17:01:27.436087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4e36a948301'
down_revision = '426ac24ff8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recovery_note', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('closed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('closed_by_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_diseases_closed_by_id_users', 'users', ['closed_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('diseases', schema=None) as batch_op:
        batch_op.drop_constraint('fk_diseases_closed_by_id_users', type_='foreignkey')
        batch_op.drop_column('closed_by_id')
        batch_op.drop_column('closed_at')
        batch_op.drop_column('recovery_note')

    # ### end Alembic commands ###
