"""add weather_readings and farm_settings climate fields

Revision ID: c76a64b7fa91
Revises: 634a174c9f1c
Create Date: 2026-07-25 06:08:58.066327

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c76a64b7fa91'
down_revision = '634a174c9f1c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('weather_readings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('temp_max_c', sa.Float(), nullable=False),
    sa.Column('humidity_at_peak', sa.Float(), nullable=False),
    sa.Column('thi', sa.Float(), nullable=False),
    sa.Column('stress_level', sa.String(length=16), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('fetched_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('weather_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_weather_readings_date'), ['date'], unique=True)

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('farm_latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('farm_longitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('thi_mild', sa.Float(), nullable=False, server_default='72.0'))
        batch_op.add_column(sa.Column('thi_moderate', sa.Float(), nullable=False, server_default='79.0'))
        batch_op.add_column(sa.Column('thi_severe', sa.Float(), nullable=False, server_default='89.0'))
        batch_op.add_column(sa.Column('thi_emergency', sa.Float(), nullable=False, server_default='98.0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('thi_emergency')
        batch_op.drop_column('thi_severe')
        batch_op.drop_column('thi_moderate')
        batch_op.drop_column('thi_mild')
        batch_op.drop_column('farm_longitude')
        batch_op.drop_column('farm_latitude')

    with op.batch_alter_table('weather_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_weather_readings_date'))

    op.drop_table('weather_readings')
    # ### end Alembic commands ###
