"""add animal fields, farm settings quarantine days

Revision ID: c81d1c8b99aa
Revises: 066366b341e0
Create Date: 2026-07-22 18:19:04.083887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c81d1c8b99aa'
down_revision = '066366b341e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('father_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('color', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('name', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('entry_date', sa.Date(), nullable=True))
        batch_op.alter_column('source',
               existing_type=sa.VARCHAR(length=8),
               type_=sa.Enum('PURCHASE', 'BIRTH', 'GIFT', 'OPENING_BALANCE', name='animalsource'),
               existing_nullable=False)
        batch_op.create_foreign_key('fk_animals_father_id_animals', 'animals', ['father_id'], ['id'])

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quarantine_days', sa.Integer(), nullable=False, server_default='21'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('quarantine_days')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_constraint('fk_animals_father_id_animals', type_='foreignkey')
        batch_op.alter_column('source',
               existing_type=sa.Enum('PURCHASE', 'BIRTH', 'GIFT', 'OPENING_BALANCE', name='animalsource'),
               type_=sa.VARCHAR(length=8),
               existing_nullable=False)
        batch_op.drop_column('entry_date')
        batch_op.drop_column('image_url')
        batch_op.drop_column('name')
        batch_op.drop_column('color')
        batch_op.drop_column('father_id')

    # ### end Alembic commands ###
