"""add ostrich module (species, incubators, eggs)

Revision ID: ccfce3ef2bca
Revises: 34ff54f9f2bd
Create Date: 2026-07-23 10:37:17.820372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccfce3ef2bca'
down_revision = '34ff54f9f2bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incubators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('ostrich_eggs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mother_id', sa.Integer(), nullable=False),
    sa.Column('lay_date', sa.Date(), nullable=False),
    sa.Column('quality', sa.String(length=16), nullable=True),
    sa.Column('weight_grams', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('incubator_id', sa.Integer(), nullable=True),
    sa.Column('incubation_start_date', sa.Date(), nullable=True),
    sa.Column('hatch_result', sa.String(length=16), nullable=False),
    sa.Column('actual_hatch_date', sa.Date(), nullable=True),
    sa.Column('fail_reason', sa.Text(), nullable=True),
    sa.Column('hatched_animal_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['hatched_animal_id'], ['animals.id'], ),
    sa.ForeignKeyConstraint(['incubator_id'], ['incubators.id'], ),
    sa.ForeignKeyConstraint(['mother_id'], ['animals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.add_column(sa.Column('species', sa.String(length=20), nullable=False, server_default='sheep_goat'))

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ostrich_incubation_days', sa.Integer(), nullable=False, server_default='42'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('ostrich_incubation_days')

    with op.batch_alter_table('animals', schema=None) as batch_op:
        batch_op.drop_column('species')

    op.drop_table('ostrich_eggs')
    op.drop_table('incubators')
    # ### end Alembic commands ###
