"""add creep feed settings

Revision ID: dc500a03b442
Revises: 1b8869de3ab5
Create Date: 2026-08-22 18:28:15.794868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc500a03b442'
down_revision = '1b8869de3ab5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('creep_feed_start_age_days', sa.Integer(), nullable=False, server_default='20'))
        batch_op.add_column(sa.Column('creep_feed_target_grams_per_day', sa.Integer(), nullable=False, server_default='200'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('creep_feed_target_grams_per_day')
        batch_op.drop_column('creep_feed_start_age_days')

    # ### end Alembic commands ###
