"""add user base_salary

Revision ID: e29cc9955eb9
Revises: 8757a4a3ed0c
Create Date: 2026-08-26 11:48:36.050994

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e29cc9955eb9'
down_revision = '8757a4a3ed0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('base_salary', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('base_salary')

    # ### end Alembic commands ###
