"""add requires_isolation to disease symptom link

Revision ID: e2ec18170483
Revises: 33bfa760a676
Create Date: 2026-08-06 01:08:38.375399

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2ec18170483'
down_revision = '33bfa760a676'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_symptom_links', schema=None) as batch_op:
        batch_op.add_column(sa.Column('requires_isolation', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('disease_symptom_links', schema=None) as batch_op:
        batch_op.drop_column('requires_isolation')

    # ### end Alembic commands ###
