"""add implicit pregnancy detection settings

Revision ID: e3bebbcda118
Revises: dc500a03b442
Create Date: 2026-08-26 08:53:05.197146

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bebbcda118'
down_revision = 'dc500a03b442'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estrus_return_window_days', sa.Integer(), nullable=False, server_default='21'))
        batch_op.add_column(sa.Column('implicit_pregnancy_sonar_check_days', sa.Integer(), nullable=False, server_default='45'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('implicit_pregnancy_sonar_check_days')
        batch_op.drop_column('estrus_return_window_days')

    # ### end Alembic commands ###
