"""add emergency symptoms table

Revision ID: e78394e319da
Revises: e2ec18170483
Create Date: 2026-08-06 08:24:01.891551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e78394e319da'
down_revision = 'e2ec18170483'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('emergency_symptoms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symptom_id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('differential', sa.Text(), nullable=False),
    sa.Column('advice', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['symptom_id'], ['symptoms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('symptom_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emergency_symptoms')
    # ### end Alembic commands ###
