"""add medicine_class, planned treatment fields, reweigh/redose settings

Revision ID: ea181a74cbd0
Revises: c76a64b7fa91
Create Date: 2026-07-25 08:52:38.425393

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea181a74cbd0'
down_revision = 'c76a64b7fa91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reweigh_followup_days', sa.Integer(), nullable=False, server_default='14'))
        batch_op.add_column(sa.Column('antiparasitic_redose_days', sa.Integer(), nullable=False, server_default='30'))

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('medicine_class', sa.String(length=20), nullable=True))

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planned_pharmacy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('planned_quantity', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('planned_treatment_kind', sa.String(length=16), nullable=True))
        batch_op.create_foreign_key('fk_tasks_planned_pharmacy_id', 'pharmacy', ['planned_pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_planned_pharmacy_id', type_='foreignkey')
        batch_op.drop_column('planned_treatment_kind')
        batch_op.drop_column('planned_quantity')
        batch_op.drop_column('planned_pharmacy_id')

    with op.batch_alter_table('pharmacy', schema=None) as batch_op:
        batch_op.drop_column('medicine_class')

    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_column('antiparasitic_redose_days')
        batch_op.drop_column('reweigh_followup_days')

    # ### end Alembic commands ###
