"""add optional english barn name

Revision ID: f355844bfa11
Revises: 5244dce3cc23
Create Date: 2026-08-31 04:03:45.153470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f355844bfa11'
down_revision = '5244dce3cc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barns', schema=None) as batch_op:
        batch_op.add_column(sa.Column('barn_name_en', sa.String(length=120), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('barns', schema=None) as batch_op:
        batch_op.drop_column('barn_name_en')

    # ### end Alembic commands ###
