"""add is_indirect to finance

Revision ID: f4365b27d099
Revises: a8cabddedf0c
Create Date: 2026-07-24 03:43:30.115882

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4365b27d099'
down_revision = 'a8cabddedf0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_indirect', sa.Boolean(), nullable=False, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('finance', schema=None) as batch_op:
        batch_op.drop_column('is_indirect')

    # ### end Alembic commands ###
