"""add user specialty field (band 267)

Revision ID: fc4035f84b69
Revises: 9444d4ca253d
Create Date: 2026-08-27 04:17:19.196270

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc4035f84b69'
down_revision = '9444d4ca253d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialty', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('specialty')

    # ### end Alembic commands ###
