"""default intake spray/vaccine pharmacy settings (band 283)

Revision ID: fddf213c052a
Revises: 955f13951cc4
Create Date: 2026-08-28 12:51:33.291703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fddf213c052a'
down_revision = '955f13951cc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('default_intake_spray_pharmacy_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('default_intake_vaccine_pharmacy_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_farm_settings_intake_spray_pharmacy', 'pharmacy',
                                     ['default_intake_spray_pharmacy_id'], ['id'])
        batch_op.create_foreign_key('fk_farm_settings_intake_vaccine_pharmacy', 'pharmacy',
                                     ['default_intake_vaccine_pharmacy_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('farm_settings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_farm_settings_intake_vaccine_pharmacy', type_='foreignkey')
        batch_op.drop_constraint('fk_farm_settings_intake_spray_pharmacy', type_='foreignkey')
        batch_op.drop_column('default_intake_vaccine_pharmacy_id')
        batch_op.drop_column('default_intake_spray_pharmacy_id')

    # ### end Alembic commands ###
